name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the 'main' branch (adjust if you're using a different default branch)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Node.js version to use (adjust as necessary)

    - name: Install dependencies
      run: npm install

    - name: Build the website
      run: npm run build  # Use the build command for your website (if you're using a build tool)

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4  # Use the latest stable version of the action
      with:
        branch: gh-pages  # The branch GitHub Pages will use to serve the site
        folder: build  # The folder to deploy (adjust if your build output is different)
        token: ${{ secrets.GITHUB_TOKEN }}  # Automatically generated GitHub token to authenticate the action
